services:
 #docker container #can have multiple containers to form a service
 web:
  build:
   context: .
  #ports: #wsl port, docker container port
  ports:
  - 4000:9000
  volumes:
  - ./:/app

#sample if i want to run a service with database
#  mysqldb:
#   image: mysql
#   ports:
#   - 3306:3306
#   environment:
#   - MYSQL_ROOT_PASSWORD=p@ssw0rd1
#   volumes:
#   - mysql:/var/lib/mysql
#   - mysql_config:/etc/mysql 

volumes:
  mysql:
  mysql_config: